### ISSUE TITLE
Can't remove all entries on the list

### ISSUE THREAD

**Issue by hanyuwei70** [FoxAuth/FoxAuth#11]
**Describe the bug**
When I tried to delete all entries, it can't be done and always left a blank entry.

**To Reproduce**
1. Go to 'secret token'
2. Click on 'cross of the last entry'
3.Confirm The warning

**Expected behavior**
Last entry should be deleted

**Desktop:**
 - OS: Windows 10 1803
 - Firefox 63
- Plugin No version number available

**Comment by Riajyuu** [comment]
> always left a blank entry

By design

**Comment by Riajyuu** [comment]
I did found something else.

**Comment by Riajyuu** [comment]
shall be fixed in 5b4eee522977654cc9b2a1ef1dc14db282f082ab and f9ee1d6b3364ada98e9f09dedc5de43833b00899
