### ISSUE TITLE
Display Account name in list

### ISSUE THREAD

**Issue by fython** [FoxAuth/FoxAuth#15]
If I have many accounts from a same site, I can't distinguish which 2FA code I want if I forgot their order.

Please display items' "Account name" in list. They have been already set but it looks not work.

![image](https://user-images.githubusercontent.com/3166782/48351432-35c74e00-e6c5-11e8-9d34-d96529422f5a.png)
(PS: Don't mind that "Error" text. I filled a wrong key for the second item.)

**Comment by Riajyuu** [comment]
It doesn't matter even if you actually forget them.
FoxAuth will autoly recognize Container environment and fill correctly (so we also recommend using Container for multiple accounts on README).
Also you want to edit correspondingly, simply hint the website logo.
Let me know if these two features are what you are to.

**Comment by Riajyuu** [comment]
closed for now as stale.

**Comment by Riajyuu** [comment]
reopen because of our changes at 1.4.5

**Comment by Riajyuu** [comment]
@fython any thought if we shall use special fonts or something?

**Comment by Riajyuu** [comment]
fixed in 957cd4a825a6f57f97aa6e1321d18809d8630d53
